# Generated by Django 6.0.6 on 2026-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
